version: '2'
services: 

  php72:
    image: php:7.2.10-fpm-alpine
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ${SOURCE_DIR}:${DESTINATION_DIR}
    expose:
      - "9000"

  php71:
    image: php:7.1.22-fpm-alpine
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ${SOURCE_DIR}:${DESTINATION_DIR}
    expose:
      - "9000"

  php70:
    image: php:7.0.32-fpm-alpine
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ${SOURCE_DIR}:${DESTINATION_DIR}
    expose:
      - "9000"

  php56:
    image: php:5.6.38-fpm-alpine
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ${SOURCE_DIR}:${DESTINATION_DIR}
    expose:
      - "9000"

  php55:
    image: php:5.5.38-fpm-alpine
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./php/conf.d/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ${SOURCE_DIR}:${DESTINATION_DIR}
    expose:
      - "9000"

  nginx:
    image: nginx:1.15.5-alpine
    build: ./nginx/
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
      - ${SOURCE_DIR}:${DESTINATION_DIR}
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=php72.dev.localhost
      - NGINX_HOST=php71.dev.localhost
      - NGINX_HOST=php70.dev.localhost
      - NGINX_HOST=php7.dev.localhost
      - NGINX_HOST=php56.dev.localhost
      - NGINX_HOST=php55.dev.localhost
      - NGINX_HOST=php5.dev.localhost
