version: '2'
services: 
  php:
    image: peerapongsam/php:7.1-fpm-alpine
    build: ./php/
    container_name: php_fpm
    restart: always
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"

  nginx:
    image: peerapongsam/nginx:1.13-alpine
    build: ./nginx/
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=test.dev.localhost
      - NGINX_HOST=test2.dev.localhost
